site_name: 希望你永远用不到
repo_url: https://github.com/orcas-lab/hope-you-dont-need-it
repo_name: orcas-lab/hope-you-dont-need-it
theme:
  name: 'material'
  custom_dir: overrides
  palette:
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - admonition
  - footnotes
plugins:
  - mermaid2
extra:
  disqus: 'open' # 评论系统
  generator: false