site_name: 希望你永远用不到
repo_url: https://github.com/GaoNeng-wWw/hope-you-dont-need-it
repo_name: GaoNeng-wWw/hope-you-dont-need-it
theme:
  name: 'material'
  custom_dir: overrides
markdown_extensions:
  - admonition
  - footnotes
plugins:
  - mermaid2
extra:
  disqus: 'open' # 评论系统